### ISSUE TITLE
Crash on EAP version of Scala plugin

### ISSUE THREAD

**Issue by oleg-py** [Thangiee/Freasy-Monad#8]
I use Intellij EAP version with Scala plugin on EAP update channel. Today I got a notification that update for Scala plugin is available and updated to version `2016.3.2.35`. After doing so, I get an exception in Freasy Monad plugin (version `0.5.0`) [**(long stack trace here)**](https://gist.githubusercontent.com/oleg-py/44cd24ff95b5dd4ec44ca78bac36b03f/raw/f7d8a91648a9bee60a3386c60e3830893778c37a/exception.txt) and even syntax highlighting doesn't work at all afterwards. It does work on Scala plugin from release channel, but that one makes half my code red so it's not an option.

I wonder if a plugin compatible with EAP Scala can be released.

**Comment by Thangiee** [comment]
Okay, I'll take a look at it.

Thanks for reporting the bug.

**Comment by Thangiee** [comment]
So I can't seem to reproduce this issue. I am also on the latest Intellij EAP build and Scala plugin version. 

Might be some compatibility [issue](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206638605/comments/205786115) so I updated the plugin info. Could you try the new plugin version to see if the problem is still there?
 https://github.com/Thangiee/Freasy-Monad/blob/master/plugin/bin/freasy-monad-plugin-0.5.1.zip

**Comment by oleg-py** [comment]
Yes, no errors in this plugin version. Many thanks!
